name: 'Threat Model'
description: 'Update plextrac with the latest details if this issue/pr is labeled as threat model'
inputs:
  issue:  # issue Object
    description: 'The issue triggering this workflow'
    required: true
    default: false
outputs:
  success: # boolean
    description: 'Whether this job ran successfully'
runs:
  using: 'node16'
  main: 'dist/index.js'