name: "Threat Model"
description: "Update plextrac with the latest details if this issue/pr is labeled as threat model"
inputs:
  githubToken: # token for action to access repo
    description: "The token of this workflow granting access to the repo"
    requred: true
  repository:
    description: 'The full name of the repository containing the issue or pull request.'
    default: ${{ github.repository }}
outputs:
  success: # boolean
    description: "Whether this job ran successfully"
runs:
  using: "node16"
  main: "dist/index.js"
